---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: k-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - scottames/ghostty
        - monkeygold/nautilus-open-any-terminal
    install:
      packages:
        - ghostty
        - podman
        - podman-compose
        - podman-docker
        - nautilus-open-any-terminal
        - toolbox
        - fish
        - neovim
        - openresolv
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - ptyxis
        - gnome-terminal
        - gnome-terminal-nautilus
        - gnome-tour
        - gnome-classic-session
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-background-logo
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list
        - gnome-software
        - gnome-tweaks
        - gnome-system-monitor
        - fedora-flathub-remote
        - fedora-third-party
        - fedora-workstation-repositories
        - fedora-chromium-config
        - fedora-workstation-backgrounds
        - fedora-bookmarks
        - htop
        - nvtop
        - yelp

  - type: default-flatpaks
    configurations:
      - install:
          # Gnome Core Apps
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Snapshot
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.Connections
          - org.gnome.baobab
          - org.gnome.SimpleScan
          - org.gnome.Evince
          - org.gnome.font-viewer
          - org.gnome.Loupe
          - org.gnome.Logs
          - org.gnome.TextEditor
          - org.gnome.Epiphany

          # OS Utilities
          - io.missioncenter.MissionCenter
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - com.mattjakeman.ExtensionManager
          - it.mijorus.smile
          - org.gnome.World.Iotas
          - org.gnome.NautilusPreviewer
          - com.rafaelmardojai.Blanket
          - app.drey.Warp
          - it.mijorus.gearlever
          - org.altlinux.Tuner

          # Browsers
          - com.vivaldi.Vivaldi
          - org.mozilla.firefox
          - org.chromium.Chromium

          # Entertainment
          - org.jeffvli.feishin
          - org.jellyfin.JellyfinDesktop
          - io.mpv.Mpv
          - com.moonlight_stream.Moonlight
          - com.valvesoftware.Steam
          - io.github.Foldex.AdwSteamGtk

          # Communication
          - com.discordapp.Discord
          - org.signal.Signal
          - com.slack.Slack
          - org.zulip.Zulip

          # Development
          - com.rafaelmardojai.SharePreview
          - com.mardojai.ForgeSparks
          - org.gimp.GIMP
          - org.mapeditor.Tiled
          - com.usebruno.Bruno

          - org.libreoffice.LibreOffice

  - type: gschema-overrides
    include:
      - zz1-k-os.gschema.override

  - type: brew
    brew-analytics: false

  - type: gnome-extensions
    install:
      - 4269 # Alphabetical App Grid
      - 1262 # Bing Wallpaper
      - 517 # Caffeine
      - 7065 # Tiling Shell

  - type: script
    snippets:
      # Remove the Ghostty nautilus extension
      #
      # Not sure why but it doesn't show up until I also enable the
      # open-any-terminal extension which then creates a duplicate.
      - "rm -f /usr/share/nautilus-python/extensions/ghostty.py"
      # Hide unneeded desktop entries
      - echo "Hidden=true" | tee -a
        /usr/share/applications/{nvidia-settings,fish,nvim}.desktop

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
