---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: k-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - scottames/ghostty
        - monkeygold/nautilus-open-any-terminal
    install:
      packages:
        - ghostty
        - podman
        - podman-compose
        - podman-docker
        - nautilus-open-any-terminal
        - toolbox
        - fish
        - neovim
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - ptyxis
        - gnome-terminal
        - gnome-terminal-nautilus
        - gnome-tour
        - gnome-classic-session
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-background-logo
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list
        - gnome-software
        - gnome-tweaks
        - gnome-system-monitor
        - fedora-flathub-remote
        - fedora-third-party
        - fedora-workstation-repositories
        - fedora-chromium-config
        - mediawriter
        - htop
        - nvtop
        - yelp

  - type: gschema-overrides
    include:
      - zz1-k-os.gschema.override

  - type: script
    snippets:
      # Remove the Ghostty nautilus extension
      #
      # Not sure why but it doesn't show up until I also enable the
      # open-any-terminal extension which then creates a duplicate.
      - "rm -f /usr/share/nautilus-python/extensions/ghostty.py"

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
